#!/usr/bin/env python3
import datetime
import os

# icon template
fa_icon = "<span font='Font Awesome 5 Free'>{}</span>"
# icons
calendar = fa_icon.format("\uf1ec")
clock = fa_icon.format("\uf017")

now = datetime.datetime.now()

shorttext = " {} <b>{}</b>".format(calendar, now.strftime("%d/%m/%Y"))
fulltext = shorttext + "  {} {}".format(clock, now.strftime("%H:%M:%S"))
fulltext = fulltext

button = int(os.getenv("BLOCK_BUTTON", 0))

print(fulltext)
print(shorttext)

if button == 1:
  os.system("chromium --app=https://calendar.google.com")
